# Generated by Django 5.1.7 on 2025-03-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reyting',
            field=models.IntegerField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
